const ptBookArray = [
    {code: "GEN", categories:['ot', 'pentateuch']},
    {code: "EXO", categories:['ot', 'pentateuch']},
    {code: "LEV", categories:['ot', 'pentateuch']},
    {code: "NUM", categories:['ot', 'pentateuch']},
    {code: "DEU", categories:['ot', 'pentateuch']},
    {code: "JOS", categories:['ot', 'history']},
    {code: "JDG", categories:['ot', 'history']},
    {code: "RUT", categories:['ot', 'history']},
    {code: "1SA", categories:['ot', 'history']},
    {code: "2SA", categories:['ot', 'history']},
    {code: "1KI", categories:['ot', 'history']},
    {code: "2KI", categories:['ot', 'history']},
    {code: "1CH", categories:['ot', 'history']},
    {code: "2CH", categories:['ot', 'history']},
    {code: "EZR", categories:['ot', 'history']},
    {code: "NEH", categories:['ot', 'history']},
    {code: "EST", categories:['ot', 'history']},
    {code: "JOB", categories:['ot', 'wisdom']},
    {code: "PSA", categories:['ot', 'wisdom']},
    {code: "PRO", categories:['ot', 'wisdom']},
    {code: "ECC", categories:['ot', 'wisdom']},
    {code: "SNG", categories:['ot', 'wisdom']},
    {code: "ISA", categories:['ot', 'prophecy']},
    {code: "JER", categories:['ot', 'prophecy']},
    {code: "LAM", categories:['ot', 'prophecy']},
    {code: "EZK", categories:['ot', 'prophecy']},
    {code: "DAN", categories:['ot', 'prophecy']},
    {code: "HOS", categories:['ot', 'prophecy']},
    {code: "JOL", categories:['ot', 'prophecy']},
    {code: "AMO", categories:['ot', 'prophecy']},
    {code: "OBA", categories:['ot', 'prophecy']},
    {code: "JON", categories:['ot', 'prophecy']},
    {code: "MIC", categories:['ot', 'prophecy']},
    {code: "NAM", categories:['ot', 'prophecy']},
    {code: "HAB", categories:['ot', 'prophecy']},
    {code: "ZEP", categories:['ot', 'prophecy']},
    {code: "HAG", categories:['ot', 'prophecy']},
    {code: "ZEC", categories:['ot', 'prophecy']},
    {code: "MAL", categories:['ot', 'prophecy']},
    {code: "MAT", categories:['nt', 'gospel', 'synoptic']},
    {code: "MRK", categories:['nt', 'gospel', 'synoptic']},
    {code: "LUK", categories:['nt', 'gospel', 'synoptic']},
    {code: "JHN", categories:['nt', 'gospel']},
    {code: "ACT", categories:['nt', 'gospel']},
    {code: "ROM", categories:['nt', 'epistle']},
    {code: "1CO", categories:['nt', 'epistle']},
    {code: "2CO", categories:['nt', 'epistle']},
    {code: "GAL", categories:['nt', 'epistle']},
    {code: "EPH", categories:['nt', 'epistle']},
    {code: "PHP", categories:['nt', 'epistle']},
    {code: "COL", categories:['nt', 'epistle']},
    {code: "1TH", categories:['nt', 'epistle']},
    {code: "2TH", categories:['nt', 'epistle']},
    {code: "1TI", categories:['nt', 'epistle']},
    {code: "2TI", categories:['nt', 'epistle']},
    {code: "TIT", categories:['nt', 'epistle']},
    {code: "PHM", categories:['nt', 'epistle']},
    {code: "HEB", categories:['nt', 'epistle']},
    {code: "JAS", categories:['nt', 'epistle']},
    {code: "1PE", categories:['nt', 'epistle']},
    {code: "2PE", categories:['nt', 'epistle']},
    {code: "1JN", categories:['nt', 'epistle']},
    {code: "2JN", categories:['nt', 'epistle']},
    {code: "3JN", categories:['nt', 'epistle']},
    {code: "JUD", categories:['nt', 'epistle']},
    {code: "REV", categories:['nt', 'epistle']},
    {code: "TOB", categories:['dc']},
    {code: "JDT", categories:['dc']},
    {code: "ESG", categories:['dc', 'history']},
    {code: "WIS", categories:['dc', 'wisdom']},
    {code: "SIR", categories:['dc', 'wisdom']},
    {code: "BAR", categories:['dc', 'prophecy']},
    {code: "LJE", categories:['dc']},
    {code: "S3Y", categories:['dc']},
    {code: "SUS", categories:['dc']},
    {code: "BEL", categories:['dc']},
    {code: "1MA", categories:['dc']},
    {code: "2MA", categories:['dc']},
    {code: "3MA", categories:['dc']},
    {code: "4MA", categories:['dc']},
    {code: "1ES", categories:['dc']},
    {code: "2ES", categories:['dc']},
    {code: "MAN", categories:['dc']},
    {code: "PS2", categories:['dc']},
    {code: "ODA", categories:['dc']},
    {code: "PSS", categories:['dc']},
    {code: "JSA", categories:['dc']},
    {code: "JDB", categories:['dc']},
    {code: "TBS", categories:['dc']},
    {code: "SST", categories:['dc']},
    {code: "DNT", categories:['dc']},
    {code: "BLT", categories:['dc']},
    {code: "EZA", categories:['dc']},
    {code: "5EZ", categories:['dc']},
    {code: "6EZ", categories:['dc']},
    {code: "DAG", categories:['dc']},
    {code: "PS3", categories:['dc']},
    {code: "2BA", categories:['dc']},
    {code: "LBA", categories:['dc']},
    {code: "JUB", categories:['dc']},
    {code: "ENO", categories:['dc']},
    {code: "1MQ", categories:['dc']},
    {code: "2MQ", categories:['dc']},
    {code: "3MQ", categories:['dc']},
    {code: "REP", categories:['dc']},
    {code: "4BA", categories:['dc']},
    {code: "LAO", categories:['dc']},
];

let ptBooks = {};
for (const br of ptBookArray.entries()) {
    ptBooks[br[1].code] = {...br[1], position: br[0]};
}

export { ptBookArray, ptBooks };
